services:
  - type: web
    name: shoppiq-backend
    env: python
    plan: free
    buildCommand: |
      python --version
      pip install -r requirements.txt
    startCommand: python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_API_URL
        sync: false